const fs = require('fs');
const path = require('path');

const enKeys = {
  "events.hero.badge": "Event Marketplace",
  "events.hero.title": "Live Briefs & Quick Event Setup",
  "events.hero.subtitle": "Create event requirements and connect with verified artists. Browse live event briefs or setup a quick brief for performers across India.",
  "events.hero.createButton": "+ Create Event Brief",
  "events.hero.exploreAll": "Explore All",
  "events.hero.featuredExperience": "Featured Experience",
  "events.hero.featuredTitle": "Discover Extraordinary Live Performances",
  
  "events.empty.title": "No Live Events Currently",
  "events.empty.text": "We're brewing up extraordinary new experiences. Check back shortly, or post a new event brief to summon our premier artists.",
  "events.empty.button": "Post an Event Brief",

  "events.card.budget": "Budget",
  "events.card.flexible": "Flexible",
  "events.card.performance": "Performance",

  "events.modal.title": "Post a New Requirement",
  "events.modal.eventName": "Event Name",
  "events.modal.eventNamePlaceholder": "e.g. Wedding Reception Performance",
  "events.modal.totalBudget": "Total Budget (₹)",
  "events.modal.totalBudgetPlaceholder": "50000",
  "events.modal.location": "Event Location",
  "events.modal.locationPlaceholder": "e.g. Pune, Maharashtra",
  "events.modal.date": "Event Date",
  "events.modal.performanceType": "Performance Type",
  "events.modal.selectType": "Select type…",
  "events.modal.categories": "Event Categories (Select tag chips)",
  "events.modal.requirements": "Professional Requirements",
  "events.modal.requirementsPlaceholder": "Describe your event requirements...",
  "events.modal.submitting": "Submitting Brief…",
  "events.modal.submit": "Submit Event Brief",
  "events.modal.successTitle": "Brief Submitted!",
  "events.modal.successText": "Your event requirement has been successfully created and submitted for admin review.",

  "events.toast.signinRequired": "Sign in required",
  "events.toast.signinRequiredText": "Please log in to submit an event brief.",
  "events.toast.submitting": "📋 Submitting brief…",
  "events.toast.connecting": "Connecting to MyKalaakar database.",
  "events.toast.success": "Brief submitted successfully! 🎉",
  "events.toast.successText": "Your requirement has been submitted and is pending admin approval.",
  "events.toast.failed": "Submission failed ⚠️",
  "events.toast.failedText": "Could not save event to database.",
  "events.toast.authRequired": "Authentication Required",
  "events.toast.authRequiredText": "Please sign in or register to create event briefs.",
  "events.toast.dbIssue": "Database connection issue",
  "events.toast.dbIssueText": "Stale data may be displayed. Retrying.",

  "profile.title": "My Account",
  "profile.tabs.profile": "My Profile",
  "profile.tabs.bookings": "My Bookings",
  "profile.tabs.saved": "Saved Artists",
  "profile.buttons.adminConsole": "Admin Console",
  "profile.buttons.artistDashboard": "Artist Dashboard",
  "profile.buttons.viewPublic": "View Public Page",
  
  "profile.photo.change": "Change Photo",
  "profile.form.name": "Full Name",
  "profile.form.username": "Username",
  "profile.form.phone": "Phone",
  "profile.form.access": "Access",
  "profile.form.save": "Save Profile",
  "profile.form.saving": "Saving...",
  "profile.toast.invalidType": "Invalid File Type",
  "profile.toast.invalidTypeText": "Only image files are allowed.",
  "profile.toast.tooLarge": "File Too Large",
  "profile.toast.tooLargeText": "Image size must be less than 5MB.",
  "profile.toast.saveSuccess": "Profile saved",
  "profile.toast.saveSuccessText": "Your account profile is up to date.",
  "profile.toast.saveFailed": "Profile not saved",
  "profile.toast.saveFailedText": "Could not save your profile.",
  
  "profile.access.adminPending": "Admin Request Pending",
  "profile.access.artistRejected": "Artist — Application Rejected",
  "profile.access.artistPending": "Artist — Pending Review",
  "profile.access.customer": "Customer",
  "profile.access.adminTitle": "Administration Access",
  "profile.access.adminApply": "Apply for Admin Access",
  "profile.access.adminDesc": "Submit a request to be reviewed by the platform administrators for elevated permissions.",
  "profile.toast.requestSubmitted": "Request Submitted",
  "profile.toast.requestSubmittedText": "Your admin access request has been submitted for review.",
  "profile.toast.requestFailed": "Request Failed",
  "profile.toast.requestFailedText": "Could not submit admin request. Please try again.",

  "profile.saved.emptyTitle": "No saved artists yet",
  "profile.saved.emptyText": "Hit the SAVE button on any artist profile to bookmark them here for quick access.",
  "profile.saved.explore": "Explore Artists",
  "profile.saved.browseMore": "Browse More",
  "profile.saved.savedCount": "{{count}} artist saved",
  "profile.saved.savedCountPlural": "{{count}} artists saved",
  "profile.saved.retry": "Retry",
  "profile.saved.error": "Could not load saved artists. Please try again.",
  "profile.saved.signinRequired": "Please sign in to view your saved artists.",

  "profile.bookings.title": "My Event Bookings",
  "profile.bookings.empty": "No bookings found. Visit artist profiles to book calendar holds.",
  "profile.bookings.gateway": "Gateway:",
  "profile.bookings.escrowHold": "Escrow Hold:",
  "profile.bookings.escrowPayout": "Escrow Payout:",
  "profile.bookings.diffTitle": "Negotiation Counter-Offer Diff",
  "profile.bookings.original": "Original Request",
  "profile.bookings.counter": "Counter Proposal",
  "profile.bookings.price": "Price:",
  "profile.bookings.date": "Date:",
  "profile.bookings.time": "Time:",
  "profile.bookings.location": "Location:",
  "profile.bookings.notes": "Notes:",
  "profile.bookings.disputeFiled": "Dispute Filed:",
  "profile.bookings.btnViewAgreement": "View Agreement",
  "profile.bookings.btnCancelRequest": "Cancel Request",
  "profile.bookings.btnDeclineCounter": "Decline Counter",
  "profile.bookings.btnAcceptCounter": "Accept & Confirm Hold",
  "profile.bookings.btnOpenDispute": "Open Dispute",
  "profile.bookings.btnReleaseEscrow": "Release Escrow Payout",
  "profile.bookings.btnCancelBooking": "Cancel Booking",

  "profile.bookings.cancelModal.title": "Cancel Request & Refund Calculator",
  "profile.bookings.cancelModal.prompt": "Are you sure you want to cancel this booking?",
  "profile.bookings.cancelModal.eligible": "Refund Eligible Days: {{percentage}}% refund",
  "profile.bookings.cancelModal.amount": "Refund Amount: Rs {{amount}}",
  "profile.bookings.cancelModal.note": "Funds will be returned to your payment account according to the artist's configured cancellation window policy.",
  "profile.bookings.cancelModal.btnNo": "No, Keep Hold",
  "profile.bookings.cancelModal.btnConfirm": "Confirm Cancellation",
  "profile.bookings.toast.cancelConfirmed": "Cancellation Confirmed",
  "profile.bookings.toast.cancelFailed": "Cancellation failed",

  "profile.bookings.disputeModal.title": "File Booking Dispute",
  "profile.bookings.disputeModal.categoryLabel": "Dispute Claim Category",
  "profile.bookings.disputeModal.catNoShow": "Artist No-Show",
  "profile.bookings.disputeModal.catLate": "Late Arrival",
  "profile.bookings.disputeModal.catMismatch": "Service Scope Mismatch",
  "profile.bookings.disputeModal.catFraud": "Fraudulent Behavior",
  "profile.bookings.disputeModal.detailLabel": "Detail Dispute Claims",
  "profile.bookings.disputeModal.detailPlaceholder": "Describe specifically what went wrong (evidence details, scope discrepancy, etc.)",
  "profile.bookings.disputeModal.btnCancel": "Cancel",
  "profile.bookings.disputeModal.btnSubmit": "Submit Dispute Hold",
  "profile.bookings.toast.disputeSuccess": "Dispute Filed Successfully",
  "profile.bookings.toast.disputeFailed": "Failed to file dispute.",

  "profile.bookings.authModal.title": "Additional Payment Auth",
  "profile.bookings.authModal.originalHold": "Original Authorized Hold: Rs {{amount}}",
  "profile.bookings.authModal.newHold": "New Counter proposed Price: Rs {{amount}}",
  "profile.bookings.authModal.extraHold": "Extra Hold Amount to Authorize: Rs {{amount}}",
  "profile.bookings.authModal.gateway": "Simulated {{gateway}} Gateway",
  "profile.bookings.authModal.cardName": "Cardholder Name",
  "profile.bookings.authModal.cardNumber": "Card Number",
  "profile.bookings.authModal.btnCancel": "Cancel",
  "profile.bookings.authModal.btnAuthorize": "Authorize Extra Hold",
  "profile.bookings.toast.authSuccess": "Payment Order Created",
  "profile.bookings.toast.authFailed": "Confirmation failed",
  "profile.bookings.toast.rejectSuccess": "Offer Rejected",
  "profile.bookings.toast.rejectFailed": "Failed to reject counter offer.",
  "profile.bookings.toast.releaseSuccess": "Payout Released",
  "profile.bookings.toast.releaseFailed": "Failed to release payout.",

  "profile.agreement.title": "Booking Agreement",
  "profile.agreement.contractId": "Contract ID: CONTRACT-{{id}}",
  "profile.agreement.intro": "This document serves as a binding performance contract between the **Client ({{client}})** and the **Artist ({{artist}})** under the following agreed-upon terms:",
  "profile.agreement.date": "Date of Performance",
  "profile.agreement.hours": "Performance Hours",
  "profile.agreement.location": "Function Location",
  "profile.agreement.type": "Performance Type",
  "profile.agreement.escrowTitle": "1. Escrow & Fees",
  "profile.agreement.escrowBody": "The total performance rate is set at **Rs {{amount}}**. The Client has authorized this deposit in platform escrow. Payout will be released to the Artist upon event completion and dispute window resolution.",
  "profile.agreement.cancelTitle": "2. Cancellation Rules",
  "profile.agreement.cancelBody": "Cancellations are subject to platform policy. Refund rates are adjusted based on remaining days before the event starts. No refunds are available for cancellations within 7 days of the date.",
  "profile.agreement.authFooter": "AUTHORIZED & CAPTURED IN ESCROW",
  "profile.agreement.authGateway": "Approved via {{gateway}} Gateway",
  "profile.agreement.btnClose": "Close Agreement",
  "profile.agreement.btnPrint": "Print Agreement",

  "common.artist": "Artist",
  "common.artists": "Artists"
};

const mrKeys = {
  "events.hero.badge": "कार्यक्रम बाजारपेठ",
  "events.hero.title": "थेट आवश्यकता आणि त्वरित कार्यक्रम मांडणी",
  "events.hero.subtitle": "कार्यक्रमाच्या आवश्यकता तयार करा आणि सत्यापित कलाकारांशी संपर्क साधा. थेट कार्यक्रम आवश्यकता ब्राउझ करा किंवा देशभरातील कलाकारांसाठी त्वरित आवश्यकता सेट करा.",
  "events.hero.createButton": "+ कार्यक्रम आवश्यकता तयार करा",
  "events.hero.exploreAll": "सर्व पहा",
  "events.hero.featuredExperience": "वैशिष्ट्यीकृत अनुभव",
  "events.hero.featuredTitle": "असाधारण थेट सादरीकरणे शोधा",

  "events.empty.title": "सध्या कोणतेही थेट कार्यक्रम नाहीत",
  "events.empty.text": "आम्ही नवीन अनुभव तयार करत आहोत. थोड्या वेळाने पुन्हा तपासा, किंवा आमच्या प्रमुख कलाकारांना आमंत्रित करण्यासाठी नवीन कार्यक्रम आवश्यकता पोस्ट करा.",
  "events.empty.button": "कार्यक्रम आवश्यकता पोस्ट करा",

  "events.card.budget": "बजेट",
  "events.card.flexible": "लवचिक",
  "events.card.performance": "सादरीकरण",

  "events.modal.title": "नवीन आवश्यकता पोस्ट करा",
  "events.modal.eventName": "कार्यक्रमाचे नाव",
  "events.modal.eventNamePlaceholder": "उदा. लग्न समारंभ सादरीकरण",
  "events.modal.totalBudget": "एकूण बजेट (₹)",
  "events.modal.totalBudgetPlaceholder": "50000",
  "events.modal.location": "कार्यक्रमाचे ठिकाण",
  "events.modal.locationPlaceholder": "उदा. पुणे, महाराष्ट्र",
  "events.modal.date": "कार्यक्रमाची तारीख",
  "events.modal.performanceType": "सादरीकरणाचा प्रकार",
  "events.modal.selectType": "प्रकार निवडा…",
  "events.modal.categories": "कार्यक्रम श्रेणी (टॅग निवडा)",
  "events.modal.requirements": "व्यावसायिक आवश्यकता",
  "events.modal.requirementsPlaceholder": "तुमच्या कार्यक्रमाच्या आवश्यकतांचे वर्णन करा...",
  "events.modal.submitting": "सबमिट करत आहे…",
  "events.modal.submit": "कार्यक्रम आवश्यकता सबमिट करा",
  "events.modal.successTitle": "आवश्यकता सबमिट केली!",
  "events.modal.successText": "तुमची कार्यक्रम आवश्यकता यशस्वीरित्या तयार केली गेली आहे आणि प्रशासकाच्या पुनरावलोकनासाठी पाठवली आहे.",

  "events.toast.signinRequired": "साइन इन आवश्यक",
  "events.toast.signinRequiredText": "कृपया कार्यक्रम आवश्यकता सबमिट करण्यासाठी लॉग इन करा.",
  "events.toast.submitting": "📋 सबमिट करत आहे…",
  "events.toast.connecting": "MyKalaakar डेटाबेसशी कनेक्ट करत आहे.",
  "events.toast.success": "आवश्यकता यशस्वीरित्या सबमिट केली! 🎉",
  "events.toast.successText": "तुमची आवश्यकता सबमिट केली आहे आणि प्रशासकाच्या मंजुरीच्या प्रतीक्षेत आहे.",
  "events.toast.failed": "सबमिशन अयशस्वी ⚠️",
  "events.toast.failedText": "डेटाबेसमध्ये कार्यक्रम जतन करू शकलो नाही.",
  "events.toast.authRequired": "प्रमाणीकरण आवश्यक",
  "events.toast.authRequiredText": "कृपया कार्यक्रम आवश्यकता तयार करण्यासाठी साइन इन किंवा नोंदणी करा.",
  "events.toast.dbIssue": "डेटाबेस कनेक्शन समस्या",
  "events.toast.dbIssueText": "जुन्या डेटाचे प्रदर्शन केले जाऊ शकते. पुन्हा प्रयत्न करत आहे.",

  "profile.title": "माझे खाते",
  "profile.tabs.profile": "माझी प्रोफाइल",
  "profile.tabs.bookings": "माझे बुकिंग्ज",
  "profile.tabs.saved": "जतन केलेले कलाकार",
  "profile.buttons.adminConsole": "प्रशासक कन्सोल",
  "profile.buttons.artistDashboard": "कलाकार डॅशबोर्ड",
  "profile.buttons.viewPublic": "सार्वजनिक पृष्ठ पहा",

  "profile.photo.change": "फोटो बदला",
  "profile.form.name": "पूर्ण नाव",
  "profile.form.username": "वापरकर्तानाव",
  "profile.form.phone": "फोन",
  "profile.form.access": "प्रवेश",
  "profile.form.save": "प्रोफाइल जतन करा",
  "profile.form.saving": "जतन करत आहे...",
  "profile.toast.invalidType": "अवैध फाईल प्रकार",
  "profile.toast.invalidTypeText": "फक्त चित्र फाईल्सना परवानगी आहे.",
  "profile.toast.tooLarge": "फाईल खूप मोठी आहे",
  "profile.toast.tooLargeText": "चित्राचा आकार ५MB पेक्षा कमी असावा.",
  "profile.toast.saveSuccess": "प्रोफाइल जतन केली",
  "profile.toast.saveSuccessText": "तुमची खाते प्रोफाइल अद्ययावत आहे.",
  "profile.toast.saveFailed": "प्रोफाइल जतन केली नाही",
  "profile.toast.saveFailedText": "तुमची प्रोफाइल जतन करू शकलो नाही.",

  "profile.access.adminPending": "प्रशासक विनंती प्रलंबित",
  "profile.access.artistRejected": "कलाकार — अर्ज नाकारला",
  "profile.access.artistPending": "कलाकार — पुनरावलोकनासाठी प्रलंबित",
  "profile.access.customer": "ग्राहक",
  "profile.access.adminTitle": "प्रशासन प्रवेश",
  "profile.access.adminApply": "प्रशासक प्रवेशासाठी अर्ज करा",
  "profile.access.adminDesc": "उन्नत परवानग्यांसाठी प्लॅटफॉर्म प्रशासकांद्वारे पुनरावलोकन करण्यासाठी विनंती सबमिट करा.",
  "profile.toast.requestSubmitted": "विनंती सबमिट केली",
  "profile.toast.requestSubmittedText": "तुमची प्रशासक प्रवेश विनंती पुनरावलोकनासाठी सबमिट केली आहे.",
  "profile.toast.requestFailed": "विनंती अयशस्वी",
  "profile.toast.requestFailedText": "प्रशासक विनंती सबमिट करू शकलो नाही. कृपया पुन्हा प्रयत्न करा.",

  "profile.saved.emptyTitle": "अद्याप कोणतेही कलाकार जतन केले नाहीत",
  "profile.saved.emptyText": "त्वरित प्रवेशासाठी कोणत्याही कलाकाराच्या प्रोफाइलवर सेव्ह बटण दाबा.",
  "profile.saved.explore": "कलाकार शोधा",
  "profile.saved.browseMore": "आणखी ब्राउझ करा",
  "profile.saved.savedCount": "{{count}} कलाकार जतन केला",
  "profile.saved.savedCountPlural": "{{count}} कलाकार जतन केले",
  "profile.saved.retry": "पुन्हा प्रयत्न करा",
  "profile.saved.error": "जतन केलेले कलाकार लोड करू शकलो नाही. कृपया पुन्हा प्रयत्न करा.",
  "profile.saved.signinRequired": "तुमचे जतन केलेले कलाकार पाहण्यासाठी कृपया साइन इन करा.",

  "profile.bookings.title": "माझे कार्यक्रम बुकिंग्ज",
  "profile.bookings.empty": "कोणतेही बुकिंग आढळले नाही. कॅलेंडर होल्ड बुक करण्यासाठी कलाकारांच्या प्रोफाइलला भेट द्या.",
  "profile.bookings.gateway": "गेटवे:",
  "profile.bookings.escrowHold": "एस्क्रो होल्ड:",
  "profile.bookings.escrowPayout": "एस्क्रो पेआउट:",
  "profile.bookings.diffTitle": "वाटाघाटी प्रति-प्रस्ताव फरक",
  "profile.bookings.original": "मूळ विनंती",
  "profile.bookings.counter": "प्रति-प्रस्ताव",
  "profile.bookings.price": "किंमत:",
  "profile.bookings.date": "तारीख:",
  "profile.bookings.time": "वेळ:",
  "profile.bookings.location": "ठिकाण:",
  "profile.bookings.notes": "नोंदी:",
  "profile.bookings.disputeFiled": "विवाद दाखल:",
  "profile.bookings.btnViewAgreement": "करार पहा",
  "profile.bookings.btnCancelRequest": "विनंती रद्द करा",
  "profile.bookings.btnDeclineCounter": "प्रति-प्रस्ताव नाकारा",
  "profile.bookings.btnAcceptCounter": "स्वीकारा आणि होल्ड निश्चित करा",
  "profile.bookings.btnOpenDispute": "विवाद उघडा",
  "profile.bookings.btnReleaseEscrow": "एस्क्रो पेआउट रीलिझ करा",
  "profile.bookings.btnCancelBooking": "बुकिंग रद्द करा",

  "profile.bookings.cancelModal.title": "विनंती रद्द करा आणि परतावा कॅल्क्युलेटर",
  "profile.bookings.cancelModal.prompt": "तुम्हाला खात्री आहे की तुम्ही हे बुकिंग रद्द करू इच्छिता?",
  "profile.bookings.cancelModal.eligible": "परतावा पात्र दिवस: {{percentage}}% परतावा",
  "profile.bookings.cancelModal.amount": "परताव्याची रक्कम: रु {{amount}}",
  "profile.bookings.cancelModal.note": "कलाकाराच्या कॉन्फिगर केलेल्या रद्दीकरण विंडो धोरणानुसार तुमच्या पेमेंट खात्यात निधी परत केला जाईल.",
  "profile.bookings.cancelModal.btnNo": "नाही, होल्ड ठेवा",
  "profile.bookings.cancelModal.btnConfirm": "रद्दीकरण निश्चित करा",
  "profile.bookings.toast.cancelConfirmed": "रद्दीकरण निश्चित",
  "profile.bookings.toast.cancelFailed": "रद्दीकरण अयशस्वी",

  "profile.bookings.disputeModal.title": "बुकिंग विवाद दाखल करा",
  "profile.bookings.disputeModal.categoryLabel": "विवाद दावा श्रेणी",
  "profile.bookings.disputeModal.catNoShow": "कलाकार गैरहजर",
  "profile.bookings.disputeModal.catLate": "उशिरा आगमन",
  "profile.bookings.disputeModal.catMismatch": "सेवा व्याप्ती जुळत नाही",
  "profile.bookings.disputeModal.catFraud": "फसवणूक वर्तन",
  "profile.bookings.disputeModal.detailLabel": "सविस्तर विवाद दावे",
  "profile.bookings.disputeModal.detailPlaceholder": "नेमके काय चुकीचे झाले त्याचे वर्णन करा (पुराव्यांचे तपशील, व्याप्तीतील तफावत इ.)",
  "profile.bookings.disputeModal.btnCancel": "रद्द करा",
  "profile.bookings.disputeModal.btnSubmit": "विवाद होल्ड सबमिट करा",
  "profile.bookings.toast.disputeSuccess": "विवाद यशस्वीरित्या दाखल",
  "profile.bookings.toast.disputeFailed": "विवाद दाखल करण्यात अयशस्वी.",

  "profile.bookings.authModal.title": "अतिरिक्त पेमेंट प्रमाणीकरण",
  "profile.bookings.authModal.originalHold": "मूळ अधिकृत होल्ड: रु {{amount}}",
  "profile.bookings.authModal.newHold": "नवीन प्रति-प्रस्तावित किंमत: रु {{amount}}",
  "profile.bookings.authModal.extraHold": "अधिकृत करण्यासाठी अतिरिक्त होल्ड रक्कम: रु {{amount}}",
  "profile.bookings.authModal.gateway": "सिम्युलेटेड {{gateway}} गेटवे",
  "profile.bookings.authModal.cardName": "कार्डधारकाचे नाव",
  "profile.bookings.authModal.cardNumber": "कार्ड क्रमांक",
  "profile.bookings.authModal.btnCancel": "रद्द करा",
  "profile.bookings.authModal.btnAuthorize": "अतिरिक्त होल्ड अधिकृत करा",
  "profile.bookings.toast.authSuccess": "पेमेंट ऑर्डर तयार केली",
  "profile.bookings.toast.authFailed": "निश्चिती अयशस्वी",
  "profile.bookings.toast.rejectSuccess": "प्रस्ताव नाकारला",
  "profile.bookings.toast.rejectFailed": "प्रति-प्रस्ताव नाकारण्यात अयशस्वी.",
  "profile.bookings.toast.releaseSuccess": "पेआउट रीलिझ केले",
  "profile.bookings.toast.releaseFailed": "पेआउट रीलिझ करण्यात अयशस्वी.",

  "profile.agreement.title": "बुकिंग करार",
  "profile.agreement.contractId": "करार आयडी: CONTRACT-{{id}}",
  "profile.agreement.intro": "हा दस्तऐवज **ग्राहक ({{client}})** आणि **कलाकार ({{artist}})** यांच्यातील खालील मान्य अटींनुसार बंधनकारक सादरीकरण करार म्हणून काम करतो:",
  "profile.agreement.date": "सादरीकरणाची तारीख",
  "profile.agreement.hours": "सादरीकरणाचे तास",
  "profile.agreement.location": "समारंभाचे ठिकाण",
  "profile.agreement.type": "सादरीकरणाचा प्रकार",
  "profile.agreement.escrowTitle": "1. एस्क्रो आणि शुल्क",
  "profile.agreement.escrowBody": "एकूण सादरीकरण दर **रु {{amount}}** निश्चित केला आहे. ग्राहकाने प्लॅटफॉर्म एस्क्रोमध्ये ही अनामत रक्कम अधिकृत केली आहे. कार्यक्रम पूर्ण झाल्यावर आणि विवाद विंडोचे निराकरण झाल्यावर कलाकाराला पेआउट दिले जाईल.",
  "profile.agreement.cancelTitle": "2. रद्दीकरण नियम",
  "profile.agreement.cancelBody": "रद्दीकरण प्लॅटफॉर्म धोरणाच्या अधीन आहेत. कार्यक्रम सुरू होण्यापूर्वी उर्वरित दिवसांवर आधारित परतावा दर समायोजित केले जातात. तारखेच्या 7 दिवसांच्या आत रद्दीकरणासाठी कोणताही परतावा उपलब्ध नाही.",
  "profile.agreement.authFooter": "एस्क्रोमध्ये अधिकृत आणि जप्त",
  "profile.agreement.authGateway": "{{gateway}} गेटवे द्वारे मंजूर",
  "profile.agreement.btnClose": "करार बंद करा",
  "profile.agreement.btnPrint": "करार मुद्रित करा",

  "common.artist": "कलाकार",
  "common.artists": "कलाकार"
};

const hiKeys = {
  "events.hero.badge": "कार्यक्रम बाज़ार",
  "events.hero.title": "लाइव आवश्यकताएं और त्वरित कार्यक्रम सेटअप",
  "events.hero.subtitle": "कार्यक्रम की आवश्यकताएं बनाएं और सत्यापित कलाकारों से जुड़ें। लाइव कार्यक्रम आवश्यकताएं ब्राउज़ करें या भारत भर के कलाकारों के लिए त्वरित आवश्यकता सेट करें।",
  "events.hero.createButton": "+ कार्यक्रम आवश्यकता बनाएं",
  "events.hero.exploreAll": "सभी देखें",
  "events.hero.featuredExperience": "विशेष रुप से प्रदर्शित अनुभव",
  "events.hero.featuredTitle": "असाधारण लाइव प्रदर्शन खोजें",

  "events.empty.title": "वर्तमान में कोई लाइव कार्यक्रम नहीं",
  "events.empty.text": "हम नए अनुभव तैयार कर रहे हैं। थोड़ी देर बाद फिर से जांचें, या हमारे प्रमुख कलाकारों को आमंत्रित करने के लिए एक नई कार्यक्रम आवश्यकता पोस्ट करें।",
  "events.empty.button": "कार्यक्रम आवश्यकता पोस्ट करें",

  "events.card.budget": "बजट",
  "events.card.flexible": "लचीला",
  "events.card.performance": "प्रदर्शन",

  "events.modal.title": "नई आवश्यकता पोस्ट करें",
  "events.modal.eventName": "कार्यक्रम का नाम",
  "events.modal.eventNamePlaceholder": "उदा. शादी का रिसेप्शन प्रदर्शन",
  "events.modal.totalBudget": "कुल बजट (₹)",
  "events.modal.totalBudgetPlaceholder": "50000",
  "events.modal.location": "कार्यक्रम का स्थान",
  "events.modal.locationPlaceholder": "उदा. पुणे, महाराष्ट्र",
  "events.modal.date": "कार्यक्रम की तारीख",
  "events.modal.performanceType": "प्रदर्शन प्रकार",
  "events.modal.selectType": "प्रकार चुनें…",
  "events.modal.categories": "कार्यक्रम श्रेणियां (टैग चुनें)",
  "events.modal.requirements": "पेशेवर आवश्यकताएं",
  "events.modal.requirementsPlaceholder": "अपने कार्यक्रम की आवश्यकताओं का वर्णन करें...",
  "events.modal.submitting": "सबमिट हो रहा है…",
  "events.modal.submit": "कार्यक्रम आवश्यकता सबमिट करें",
  "events.modal.successTitle": "आवश्यकता सबमिट की गई!",
  "events.modal.successText": "आपकी कार्यक्रम आवश्यकता सफलतापूर्वक बनाई गई है और व्यवस्थापक समीक्षा के लिए प्रस्तुत की गई है।",

  "events.toast.signinRequired": "साइन इन आवश्यक",
  "events.toast.signinRequiredText": "कृपया कार्यक्रम आवश्यकता सबमिट करने के लिए लॉग इन करें।",
  "events.toast.submitting": "📋 सबमिट हो रहा है…",
  "events.toast.connecting": "MyKalaakar डेटाबेस से जुड़ रहा है।",
  "events.toast.success": "आवश्यकता सफलतापूर्वक सबमिट की गई! 🎉",
  "events.toast.successText": "आपकी आवश्यकता प्रस्तुत कर दी गई है और व्यवस्थापक की मंजूरी की प्रतीक्षा में है।",
  "events.toast.failed": "सबमिशन विफल ⚠️",
  "events.toast.failedText": "डेटाबेस में कार्यक्रम सहेजा नहीं जा सका।",
  "events.toast.authRequired": "प्रमाणीकरण आवश्यक",
  "events.toast.authRequiredText": "कृपया कार्यक्रम आवश्यकता बनाने के लिए साइन इन या पंजीकरण करें।",
  "events.toast.dbIssue": "डेटाबेस कनेक्शन समस्या",
  "events.toast.dbIssueText": "पुराना डेटा प्रदर्शित किया जा सकता है। पुनः प्रयास किया जा रहा है।",

  "profile.title": "मेरा खाता",
  "profile.tabs.profile": "मेरी प्रोफ़ाइल",
  "profile.tabs.bookings": "मेरी बुकिंग",
  "profile.tabs.saved": "सहेजे गए कलाकार",
  "profile.buttons.adminConsole": "व्यवस्थापक सांत्वना",
  "profile.buttons.artistDashboard": "कलाकार डैशबोर्ड",
  "profile.buttons.viewPublic": "सार्वजनिक पृष्ठ देखें",

  "profile.photo.change": "फोटो बदलें",
  "profile.form.name": "पूरा नाम",
  "profile.form.username": "उपयोगकर्ता नाम",
  "profile.form.phone": "फ़ोन",
  "profile.form.access": "पहुंच",
  "profile.form.save": "प्रोफ़ाइल सहेजें",
  "profile.form.saving": "सहेजा जा रहा है...",
  "profile.toast.invalidType": "अमान्य फ़ाइल प्रकार",
  "profile.toast.invalidTypeText": "केवल चित्र फ़ाइलों की अनुमति है।",
  "profile.toast.tooLarge": "फ़ाइल बहुत बड़ी है",
  "profile.toast.tooLargeText": "चित्र का आकार 5MB से कम होना चाहिए।",
  "profile.toast.saveSuccess": "प्रोफ़ाइल सहेजी गई",
  "profile.toast.saveSuccessText": "आपकी खाता प्रोफ़ाइल अप टू डेट है।",
  "profile.toast.saveFailed": "प्रोफ़ाइल सहेजी नहीं गई",
  "profile.toast.saveFailedText": "आपकी प्रोफ़ाइल सहेजी नहीं जा सकी।",

  "profile.access.adminPending": "व्यवस्थापक अनुरोध लंबित",
  "profile.access.artistRejected": "कलाकार — आवेदन अस्वीकृत",
  "profile.access.artistPending": "कलाकार — समीक्षा के लिए लंबित",
  "profile.access.customer": "ग्राहक",
  "profile.access.adminTitle": "प्रशासन पहुंच",
  "profile.access.adminApply": "व्यवस्थापक पहुंच के लिए आवेदन करें",
  "profile.access.adminDesc": "उन्नत अनुमतियों के लिए प्लेटफ़ॉर्म व्यवस्थापकों द्वारा समीक्षा हेतु एक अनुरोध सबमिट करें।",
  "profile.toast.requestSubmitted": "अनुरोध सबमिट किया गया",
  "profile.toast.requestSubmittedText": "आपका व्यवस्थापक पहुंच अनुरोध समीक्षा के लिए सबमिट कर दिया गया है।",
  "profile.toast.requestFailed": "अनुरोध विफल",
  "profile.toast.requestFailedText": "व्यवस्थापक अनुरोध सबमिट नहीं किया जा सका। कृपया पुनः प्रयास करें।",

  "profile.saved.emptyTitle": "अभी तक कोई कलाकार सहेजा नहीं गया",
  "profile.saved.emptyText": "त्वरित पहुंच के लिए किसी भी कलाकार की प्रोफ़ाइल पर सहेजें बटन दबाएं।",
  "profile.saved.explore": "कलाकार खोजें",
  "profile.saved.browseMore": "और ब्राउज़ करें",
  "profile.saved.savedCount": "{{count}} कलाकार सहेजा गया",
  "profile.saved.savedCountPlural": "{{count}} कलाकार सहेजे गए",
  "profile.saved.retry": "पुनः प्रयास करें",
  "profile.saved.error": "सहेजे गए कलाकार लोड नहीं किए जा सके। कृपया पुनः प्रयास करें।",
  "profile.saved.signinRequired": "अपने सहेजे गए कलाकारों को देखने के लिए कृपया साइन इन करें।",

  "profile.bookings.title": "मेरे कार्यक्रम बुकिंग",
  "profile.bookings.empty": "कोई बुकिंग नहीं मिली। कैलेंडर होल्ड बुक करने के लिए कलाकारों की प्रोफ़ाइल पर जाएं।",
  "profile.bookings.gateway": "गेटवे:",
  "profile.bookings.escrowHold": "एस्क्रो होल्ड:",
  "profile.bookings.escrowPayout": "एस्क्रो भुगतान:",
  "profile.bookings.diffTitle": "बातचीत प्रति-प्रस्ताव अंतर",
  "profile.bookings.original": "मूल अनुरोध",
  "profile.bookings.counter": "प्रति-प्रस्ताव",
  "profile.bookings.price": "मूल्य:",
  "profile.bookings.date": "तारीख:",
  "profile.bookings.time": "समय:",
  "profile.bookings.location": "स्थान:",
  "profile.bookings.notes": "नोट्स:",
  "profile.bookings.disputeFiled": "विवाद दायर:",
  "profile.bookings.btnViewAgreement": "समझौता देखें",
  "profile.bookings.btnCancelRequest": "अनुरोध रद्द करें",
  "profile.bookings.btnDeclineCounter": "प्रति-प्रस्ताव अस्वीकार करें",
  "profile.bookings.btnAcceptCounter": "स्वीकार करें और होल्ड की पुष्टि करें",
  "profile.bookings.btnOpenDispute": "विवाद खोलें",
  "profile.bookings.btnReleaseEscrow": "एस्क्रो भुगतान जारी करें",
  "profile.bookings.btnCancelBooking": "बुकिंग रद्द करें",

  "profile.bookings.cancelModal.title": "अनुरोध रद्द करें और धनवापसी कैलकुलेटर",
  "profile.bookings.cancelModal.prompt": "क्या आप वाकई इस बुकिंग को रद्द करना चाहते हैं?",
  "profile.bookings.cancelModal.eligible": "धनवापसी योग्य दिन: {{percentage}}% धनवापसी",
  "profile.bookings.cancelModal.amount": "धनवापसी राशि: रु {{amount}}",
  "profile.bookings.cancelModal.note": "कलाकार की कॉन्फ़िगर की गई रद्दीकरण विंडो नीति के अनुसार आपके भुगतान खाते में धनराशि वापस कर दी जाएगी।",
  "profile.bookings.cancelModal.btnNo": "नहीं, होल्ड रखें",
  "profile.bookings.cancelModal.btnConfirm": "रद्दीकरण की पुष्टि करें",
  "profile.bookings.toast.cancelConfirmed": "रद्दीकरण की पुष्टि की गई",
  "profile.bookings.toast.cancelFailed": "रद्दीकरण विफल",

  "profile.bookings.disputeModal.title": "बुकिंग विवाद दायर करें",
  "profile.bookings.disputeModal.categoryLabel": "विवाद दावा श्रेणी",
  "profile.bookings.disputeModal.catNoShow": "कलाकार अनुपस्थित",
  "profile.bookings.disputeModal.catLate": "देर से आगमन",
  "profile.bookings.disputeModal.catMismatch": "सेवा का दायरा मेल नहीं खाता",
  "profile.bookings.disputeModal.catFraud": "धोखाधड़ी वाला व्यवहार",
  "profile.bookings.disputeModal.detailLabel": "विस्तृत विवाद दावे",
  "profile.bookings.disputeModal.detailPlaceholder": "विशेष रूप से वर्णन करें कि क्या गलत हुआ (सबूत विवरण, दायरे में विसंगति, आदि)",
  "profile.bookings.disputeModal.btnCancel": "रद्द करें",
  "profile.bookings.disputeModal.btnSubmit": "विवाद होल्ड सबमिट करें",
  "profile.bookings.toast.disputeSuccess": "विवाद सफलतापूर्वक दायर किया गया",
  "profile.bookings.toast.disputeFailed": "विवाद दायर करने में विफल।",

  "profile.bookings.authModal.title": "अतिरिक्त भुगतान प्रमाणीकरण",
  "profile.bookings.authModal.originalHold": "मूल अधिकृत होल्ड: रु {{amount}}",
  "profile.bookings.authModal.newHold": "नया प्रति-प्रस्तावित मूल्य: रु {{amount}}",
  "profile.bookings.authModal.extraHold": "अधिकृत करने के लिए अतिरिक्त होल्ड राशि: रु {{amount}}",
  "profile.bookings.authModal.gateway": "सिम्युलेटेड {{gateway}} गेटवे",
  "profile.bookings.authModal.cardName": "कार्डधारक का नाम",
  "profile.bookings.authModal.cardNumber": "कार्ड नंबर",
  "profile.bookings.authModal.btnCancel": "रद्द करें",
  "profile.bookings.authModal.btnAuthorize": "अतिरिक्त होल्ड अधिकृत करें",
  "profile.bookings.toast.authSuccess": "भुगतान आदेश बनाया गया",
  "profile.bookings.toast.authFailed": "पुष्टि विफल",
  "profile.bookings.toast.rejectSuccess": "प्रस्ताव अस्वीकार कर दिया गया",
  "profile.bookings.toast.rejectFailed": "प्रति-प्रस्ताव अस्वीकार करने में विफल।",
  "profile.bookings.toast.releaseSuccess": "भुगतान जारी किया गया",
  "profile.bookings.toast.releaseFailed": "भुगतान जारी करने में विफल।",

  "profile.agreement.title": "बुकिंग समझौता",
  "profile.agreement.contractId": "अनुबंध आईडी: CONTRACT-{{id}}",
  "profile.agreement.intro": "यह दस्तावेज़ **ग्राहक ({{client}})** और **कलाकार ({{artist}})** के बीच निम्नलिखित सहमत शर्तों के तहत एक बाध्यकारी प्रदर्शन अनुबंध के रूप में कार्य करता है:",
  "profile.agreement.date": "प्रदर्शन की तारीख",
  "profile.agreement.hours": "प्रदर्शन के घंटे",
  "profile.agreement.location": "समारोह का स्थान",
  "profile.agreement.type": "प्रदर्शन का प्रकार",
  "profile.agreement.escrowTitle": "1. एस्क्रो और शुल्क",
  "profile.agreement.escrowBody": "कुल प्रदर्शन दर **रु {{amount}}** निर्धारित की गई है। ग्राहक ने प्लेटफ़ॉर्म एस्क्रो में इस जमा को अधिकृत कर दिया है। कार्यक्रम पूरा होने और विवाद विंडो के समाधान पर कलाकार को भुगतान जारी किया जाएगा।",
  "profile.agreement.cancelTitle": "2. रद्दीकरण नियम",
  "profile.agreement.cancelBody": "रद्दीकरण प्लेटफ़ॉर्म नीति के अधीन हैं। कार्यक्रम शुरू होने से पहले शेष दिनों के आधार पर धनवापसी दरें समायोजित की जाती हैं। तारीख के 7 दिनों के भीतर रद्दीकरण के लिए कोई धनवापसी उपलब्ध नहीं है।",
  "profile.agreement.authFooter": "एस्क्रो में अधिकृत और जप्त",
  "profile.agreement.authGateway": "{{gateway}} गेटवे के माध्यम से स्वीकृत",
  "profile.agreement.btnClose": "समझौता बंद करें",
  "profile.agreement.btnPrint": "समझौता प्रिंट करें",

  "common.artist": "कलाकार",
  "common.artists": "कलाकार"
};

const locales = [
  { path: path.join(__dirname, 'src/locales/en/common.json'), keys: enKeys },
  { path: path.join(__dirname, 'src/locales/mr/common.json'), keys: mrKeys },
  { path: path.join(__dirname, 'src/locales/hi/common.json'), keys: hiKeys }
];

locales.forEach(locale => {
  const fileContent = fs.readFileSync(locale.path, 'utf8');
  let data;
  try {
    data = JSON.parse(fileContent);
  } catch (e) {
    console.error("Error parsing JSON:", locale.path);
    return;
  }
  
  // Merge keys
  Object.assign(data, locale.keys);
  
  // Write back nicely formatted
  fs.writeFileSync(locale.path, JSON.stringify(data, null, 2) + "\n", 'utf8');
  console.log(`Updated ${locale.path} with new translation keys.`);
});
